### ISSUE TITLE
Update the test suite

### ISSUE THREAD

**Issue by mperrin** [mperrin/webbpsf#1]
Test suite is completely broken following repackaging. Set up to run properly; investigate using some continuous validation tool(s).

**Comment by mperrin** [comment]
This is very generic. We've clearly made major progress since I wrote the above. 

@cslocum, about the 'continuous validation' point - right now you've got this all running as part of the SSBDEV validation suite weekly, right?  Where do the outputs of those tests go? I assume there is a web page or dashboard or something like that?

**Comment by josePhoenix** [comment]
We should maybe close this and make a more specific issue ("Set up Travis-CI"?)

**Comment by mperrin** [comment]
This has more or less been accomplished. Still need to unbreak the travis setup but this issue isn't useful any more.
