### ISSUE TITLE
Additional example showing PySynphot source spectra

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#105]
Based on conversation with @rebekah9969: We should add an example showing how to use an input spectrum with pysynphot directly, as this is kind of glossed over in the documentation. Specifically, the wavelength units for the ArraySpectrum should be Angstroms if not supplied explicitly.

http://pythonhosted.org/webbpsf/webbpsf.html#input-source-spectra

**Comment by mperrin** [comment]
Issues migrated to https://github.com/spacetelescope/webbpsf/issues. 
Please see the copies in that repo from now on.
