### ISSUE TITLE
Replace PySynphot dependency in setup.py with one that references the repo

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#129]
Looks like this is possible: http://stackoverflow.com/questions/18026980/python-setuptools-how-can-i-list-a-private-repository-under-install-requires

**Comment by josePhoenix** [comment]
Upon investigation, this workaround is not in fact possible. It was deprecated, and now it doesn't work at all. I guess we should plan ahead for the day where we have to drop PySynphot.

**Comment by mperrin** [comment]
I don't understand - isn't pysynphot still used as one of the low level infrastructure pieces in Pandeia? Why would we have to drop it?

**Comment by josePhoenix** [comment]
Because we want users to be able to install WebbPSF and POPPY using the standard Python package manager, but SSB does not want to maintain PyPI packages for pysynphot.

**Comment by mperrin** [comment]
Right. But it's already an optional dependency, so users can either go without it (and still be able to use WebbPSF just as now), or install Astroconda and get pysynphot that way. As far as I know it's going to remain available in astroconda even if not on PYPI. So I don't see a need to drop the existing functionality given that. I agree this is less than ideal though.

**Comment by mperrin** [comment]
no action needed on this at this time, especially since increasingly astroconda is the main distribution channel for all this .
