### ISSUE TITLE
PSF Library Maker enhancements

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#147]
- [ ] spit out wavelength cubes for NIRSpec (but what ranges and sampling?)
- [ ] only compute broadband PSFs with the TA filters using the `MSA all open` pupil mask on NIRSpec
- [ ] Add NIRISS NRM PSFs
- [ ] Generate plots and an HTML index file

**Comment by mperrin** [comment]
Downloadable PSF library maker has been deprecated - no need to update it. Plots and tables of PSFs are now in JDox.
