### ISSUE TITLE
How does the NIRCam model handle filters in the pupil wheel?

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#153]
When analyzing some CV3 test data, I was made aware of the fact that some filters are mounted in the pupil wheel and used with a wide filter in the filter wheel. In particular, F407N and F444W are used together.

Since WebbPSF doesn't pretend to model overall system throughput, and since the top of the F444W filter is pretty smooth in the region of F407N (as one might expect), I doubt it needs to be treated explicitly. However, a note in `jwst.rst` might not be amiss.

**Comment by mperrin** [comment]
It handles it correctly so far as I know. Remember behind the scenes all the throughput files are derived from Pandora then normalized to leave out the total throughput. The Pandeia calculation of the system spectral response does properly include both the above filters, or at least that's my understanding. Could doubled check with Tim if you want to be really sure.

**Comment by mperrin** [comment]
Pandeia not Pandora. For some reason iOS autocorrect doesn't know about the Greek goddess of brightness...

**Comment by mperrin** [comment]
stale issue, no action needed.
