### ISSUE TITLE
Add the WFIRST "blue" (orange) filter

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#167]
The WFIRST WFI has gained a shorter wavelength filter.

**Comment by josePhoenix** [comment]
CC @meredith-durbin for reference info

**Comment by meredith-durbin** [comment]
Passing the buck to @rubab1, since I got the filter curves from him

**Comment by rubab1** [comment]
The most recent filter definitions (Cycle 6) preceded selection of the Orange filter. I agree that inclusion of the new filter soon is essential, when a new curve is officially available.

**Comment by josePhoenix** [comment]
From Jeff Kruk:

> The transmission curve data are posted on the public WFIRST website:
https://wfirst.gsfc.nasa.gov/science/Instrument_Reference_Information.html
>
> If you scroll down to near the bottom of this page, the first link under 'Spreadsheets' has the full spreadsheet with all of the filters. This should be in the same format as the previous spreadsheets we have posted.
>
> We don't yet have updated zernike coefficients, but I will let you know when we have them.

**Comment by rubab1** [comment]
@josePhoenix Thanks for the link, didn't know it was public already. Let's hope for a speedy delivery of the updated zernike coefficients :-)

**Comment by mperrin** [comment]
Added by @robelgeda  as R062
