### ISSUE TITLE
otelm folder and opds.py bug

### ISSUE THREAD

**Issue by robelgeda** [mperrin/webbpsf#178]
otelm folder is not being built and multiple minor bugs spotted in opds.py.

**Comment by robelgeda** [comment]
I can't self-assign here but I am working on this.

**Comment by mperrin** [comment]
Let me know what you run into - that code was working for me locally but it's new so I'm not surprised there are issues. Thanks for helping Lauren with this today

**Comment by robelgeda** [comment]
Addressed in PR #185

**Comment by mperrin** [comment]
Fixed by #185
