### ISSUE TITLE
Add option to turn off cold pupil mask for WFIRST

### ISSUE THREAD

**Issue by ariedel** [mperrin/webbpsf#182]
The W146, F184, G150 (grism) and, depending on where you look on the Cycle 7 reference page, H158 filters on WFIRST use a cold pupil mask; the R062, Z087, Y106 and J129 filters do not.

Pandeia uses a library of monochromatic PSFs to generate observations. That means we need versions of a 0.927 micron PSF with the mask (for W146) and without the mask (for Z087 and Y106), and so on. 

I think the best way to handle this is to add a flag that overrides the default behavior.

**Comment by mperrin** [comment]
Resolved by #188.
