### ISSUE TITLE
WFIRST User Interface PSF Calculation Bug

### ISSUE THREAD

**Issue by robelgeda** [mperrin/webbpsf#183]
When using webbpsf.jupyter_gui.show_notebook_interface_wfi(wfi) for WFIRST Tools, the PSF calculation runs into the following error (NB: I am using a docker container):
<img width="798" alt="screen shot 2018-01-12 at 11 21 48 am" src="https://user-images.githubusercontent.com/10345916/34884748-b15660a8-f78b-11e7-9ec9-cb231ea60587.png">

**Comment by mperrin** [comment]
Fixed by #184 and #211
