### ISSUE TITLE
MIRI FND filter wavelength data doesn't go to short wavelengths

### ISSUE THREAD

**Issue by shanosborne** [mperrin/webbpsf#196]
Doesn't reach short enough wavelengths so the transmission goes to zero
![miri](https://user-images.githubusercontent.com/31218961/36699208-03135840-1b1a-11e8-9789-bd4f340ea374.png)

**Comment by mperrin** [comment]
Neither @shanosborne nor I can remember why we thought this was an issue.

**Comment by mperrin** [comment]
The updated filter throughput file I made for 0.7.0 has a better wavelength range.

On the other hand it has some weird narrow spikes at longer wavelengths. Not sure if real but that's what's in Pandeia. In any case, we're now going to be synced up with the official reference data used in the ETC, so further investigation of this is not our job as part of WebbPSF dev. 

![miri_fnd_throughput_updated](https://user-images.githubusercontent.com/1151745/40456187-08f5e178-5ebe-11e8-833d-e325e084498f.png)
