### ISSUE TITLE
NIRISS SOSS psfs are identical for CLEAR and F277W filters

### ISSUE THREAD

**Issue by hover2pi** [mperrin/webbpsf#227]
I noticed that if I generate a NIRISS psf using pupil `GR700XD` and filter `CLEAR` or `F277W`, I get identical psfs returned. They should be different!

Here's the code I used:

```
import webbpsf
ns = webbpsf.NIRISS()
ns.pupil_mask = 'GR700XD'
ns.filter = 'CLEAR'
clear = ns.calc_psf(monochromatic=1E-6, oversample=1)
ns.filter = 'F277W'
f277w = ns.calc_psf(monochromatic=1E-6, oversample=1)
np.all(clear == f277w)
```

Is it the case that only the `CLEAR` filter is supported with `GR700XD` or am I mistaken? And if not, are there plans to add support for the `F277W` filter? Thanks!

**Comment by mperrin** [comment]
Hi @hover2pi - apologies for not responding to this before now. We're actually using the repo in `spacetelescope/webbpsf` as the main development repo now, so I'll refile this as an issue of there.
