### ISSUE TITLE
Docs: "Performance and Parallelization" appendix out of date

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#23]
A user asked me about `webbpsf.settings.use_multiprocessing` and it looks like that's no longer supported. He saw it in [Appendix: Performance and Parallelization](http://www.stsci.edu/~mperrin/software/webbpsf/performance.html), which we should update before releasing 0.3.0.

**Comment by mperrin** [comment]
Was this handled as part of the docs refresh you just checked in, or is there still more to do on this one?

**Comment by josePhoenix** [comment]
Yes, this is done! https://github.com/mperrin/webbpsf/commit/7ae1ddc0b3d659bc1eb7708d737ac69a7216cd2b
