### ISSUE TITLE
Revalidate multiprocessing; optimize

### ISSUE THREAD

**Issue by mperrin** [mperrin/webbpsf#3]
Some of the multi-CPU options have not been tested extensively in a while. Needs to be revalidated, and the defaults possible improved. Overall an analysis of performance optimization would be a good idea.

**Comment by mperrin** [comment]
Docs have been updated (thanks!). Apart from the weirdness with multiprocessing instabilities, I would class this as a relatively low-priority item.  I think we both expect the multiprocessor stuff to be tricky to dig into, and I would say probably not worth holding up the 0.3 release for at this point?

**Comment by josePhoenix** [comment]
Agreed. We should make issues that are smaller in scope for specific improvements to multiprocessing. At least for now we have some in POPPY: https://github.com/mperrin/poppy/issues/23 https://github.com/mperrin/poppy/issues/60 https://github.com/mperrin/poppy/issues/54
