### ISSUE TITLE
NIRCam _validate_config will need to be updated to handle sources given as weights

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#31]

**Comment by mperrin** [comment]
Description: Currently this uses the filter name string to determine whether to set the pixel scale to the NIRCam short or NIRCam long scales.  Assumes the filter is a string in HST/JWST style 'F200W', 'F470N', etc. 

The suggestion was that if the user decides to specify the wavelengths and weights manually, then this filter name approach will not work, and will need to be updated. 

One minor difficulty I see is that right now _validate_config is called from inside _getOpticalSystem, and doesn't have access to the source information, which is dealt with in _getWeights. So some refactoring would be needed, and we should try to think about how to minimize how convoluted this code gets. 

I think this only makes sense to do after you merge in your Filter-as-an-object code, which I recall you telling me about a while ago. But I'm not sure if that is ready to go in 0.3?

**Comment by josePhoenix** [comment]
I think it might make sense to move the call to `_validate_config` into `Instrument.calcPSF`. At the moment it only serves to solve our immediate problem, but thinking ahead to specifying a field position (for field dependence support) we'll probably want to validate the config with info on the aperture and position. I'm imagining that the aperture will be set as an attribute or property on Instrument, and position will be passed in to calcPSF. For that case, then, we will again want to pass `_validate_config` something only `calcPSF` knows about.

**Comment by josePhoenix** [comment]
Fixed by https://github.com/mperrin/webbpsf/pull/42
