### ISSUE TITLE
Ureka aside in installation instructions no longer up-to-date

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#44]
Institute users won't be using `ur_setup common ssbdev` to set up Ureka any more. (Just `ssbx` or `ssbdev` will be enough to activate the environment.) We should update the [aside in the installation instructions](http://pythonhosted.org/webbpsf/installation.html#installing-the-required-data-files) to reflect that.

**Comment by mperrin** [comment]
I actually just did this as part of a documentation cleanup pass.
