### ISSUE TITLE
INSTRUME key in FITS filter headers always == 'NIRCam' for NIRISS, MIRI

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#66]
For consistency, these should be updated to reflect their respective instrument names when we next update the data files.

**Comment by mperrin** [comment]
MIRI filters fixed, as part of total replacement of those files with the published MIRI filters from http://www.jstor.org/stable/10.1086/682264

The NIRISS filters are in fact NIRCam flight spare hardware that was bought by NIRCam originally, so I say those header keywords are sufficiently correct as-is. :-)

**Comment by mperrin** [comment]
Will be fixed as part of #78

**Comment by mperrin** [comment]
NIRISS filters done as part of #78
