### ISSUE TITLE
Update NIRISS filter profiles in webbpsf-data

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#78]
We appear to have all the inputs in `sources` to provide better filter throughput tables for NIRISS. It's just a matter of making FITS tables out of them.

See #7 for previous context.

**Comment by mperrin** [comment]
hmm, this should probably actually happen now if at all possible.

**Comment by mperrin** [comment]
Filters updated in webbpsf-data-source using new make_updated_NIRISS_filters.ipynb in the appropriate sources directory.  Will be included in the new release as part of #80.
