### ISSUE TITLE
Test FieldDependentAberration interpolation code paths

### ISSUE THREAD

**Issue by josePhoenix** [mperrin/webbpsf#84]
I'd been using only pre-calculated field points in my testing and almost missed a Python 2/3 bug: 3c4ed55

Probably this can be done with an unphysical aberration optic that ranges from 0.0 Z1 at one corner to 1.0 Z1 at the other. Check in the middle to make sure it's 0.5.

**Comment by mperrin** [comment]
@josePhoenix can you estimate a timeline when you might get this done? If it's an easy test case to add, I'll tag it for 0.4.1 else 0.5. Your call.

**Comment by mperrin** [comment]
Stale issue; this code has been released for a long time and we've heard no complaints. No further action planned at this time.
