### ISSUE TITLE
move poppy.measure_strehl function to webbpsf and ensure it works. 

### ISSUE THREAD

**Issue by mperrin** [mperrin/webbpsf#88]
See https://github.com/mperrin/poppy/issues/138

The fix is to move that function from ``poppy`` to ``webbpsf``, fixing an oversight from when I fissioned ``poppy`` into its own package separate from ``webbpsf``.

**Comment by neilzim** [comment]
I'll also note that the `__init__.py` of webbpsf tries to import measure_strehl from poppy (at line 81), so in addition to moving the function, that statement should be corrected. Because of this, `import webbpsf` fails for the master version.

**Comment by mperrin** [comment]
right, I have this fixed in my local branch but hadn't pushed the changes to github yet. I can do that now.

**Comment by mperrin** [comment]
Code is working I believe, but we should add a unit test.

**Comment by mperrin** [comment]
Unit test added in commit  67373db
